# Generates src/zh.rs from OpenCC dictionaries (S2T: TSPhrases + TSCharacters).
# Run: py scripts/gen_zh.py  (expects /tmp/STCharacters.txt + /tmp/STPhrases.txt)

chars = {}
phrases = []


def parse(path):
    for ln in open(path, encoding='utf-8'):
        ln = ln.strip()
        if not ln or ln.startswith('#'):
            continue
        parts = ln.split('\t')
        if len(parts) != 2:
            continue
        k, v = parts[0], parts[1].split()[0]  # first candidate
        if len(k) == 1:
            chars[k] = v
        else:
            phrases.append((k, v))


parse('/tmp/STCharacters.txt')
parse('/tmp/STPhrases.txt')
# Keep only phrases whose conversion differs from per-char mapping —
# the rest are redundant (per-char pass already produces them).
def per_char(t):
    return ''.join(chars.get(c, c) for c in t)

phrases = [(k, v) for (k, v) in phrases if per_char(k) != v]
phrases.sort(key=lambda kv: -len(kv[0]))
items = sorted(chars.items(), key=lambda kv: kv[0])

head = (
    "//! Simplified-to-Traditional conversion (S2T), embedded from OpenCC\n"
    "//! (https://github.com/BYVoid/OpenCC, Apache-2.0): TSPhrases +\n"
    "//! TSCharacters (first-candidate mapping). Phrase substitutions run\n"
    "//! first, then per-char. Generated by scripts/gen_zh.py - do not edit.\n"
    "\n"
    "/// (simplified, traditional) phrase pairs, longest first.\n"
    "pub static S2T_PHRASES: &[(&str, &str)] = &[\n"
)
mid = (
    "];\n"
    "\n"
    "/// (simplified, traditional) single-char pairs, sorted by char.\n"
    "pub static S2T_CHARS: &[(char, &str)] = &[\n"
)
tail = "];\n"

with open('src/zh.rs', 'w', encoding='utf-8', newline='\n') as f:
    f.write(head)
    for k, v in phrases:
        f.write('    ("%s", "%s"),\n' % (k, v))
    f.write(mid)
    for k, v in items:
        f.write('    (\'%s\', "%s"),\n' % (k, v))
    f.write(tail)

fn = (
    "\n"
    "/// Convert simplified Chinese text to traditional.\n"
    "pub fn s2t(text: &str) -> String {\n"
    "    let mut out = text.to_string();\n"
    "    for (s, t) in S2T_PHRASES {\n"
    "        if out.contains(s) {\n"
    "            out = out.replace(s, t);\n"
    "        }\n"
    "    }\n"
    "    out.chars()\n"
    "        .map(|c| match S2T_CHARS.binary_search_by(|(k, _)| k.cmp(&c)) {\n"
    "            Ok(i) => S2T_CHARS[i].1.to_string(),\n"
    "            Err(_) => c.to_string(),\n"
    "        })\n"
    "        .collect()\n"
    "}\n"
)
with open('src/zh.rs', 'a', encoding='utf-8', newline='\n') as f:
    f.write(fn)

print('zh.rs: %d phrases, %d chars' % (len(phrases), len(items)))
